# Generated by Django 3.2.22 on 2024-01-27 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0002_homework_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='teacher_uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 22, 17, 12, 568269)),
        ),
        migrations.AddField(
            model_name='homework',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='homework_files', to='studyswift.HomeworkFile'),
        ),
    ]
