# Generated by Django 3.2.22 on 2024-01-27 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0003_auto_20240127_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 23, 34, 23, 132051)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='homework_files', to='studyswift.HomeworkFile'),
        ),
    ]
