# Generated by Django 3.2.22 on 2024-01-28 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0003_alter_homework_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 4, 19, 15, 14, 702749)
            ),
        ),
    ]
