# Generated by Django 3.2.22 on 2023-11-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0003_zoommeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ZoomMeeting',
        ),
    ]
