# Generated by Django 3.2.22 on 2024-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0004_auto_20240107_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='identifier',
            field=models.CharField(default='default_value', max_length=20, unique=True),
        ),
    ]
