# Generated by Django 3.2.22 on 2024-01-07 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyswift', '0005_schoolclass_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HomeworkAssignment',
        ),
    ]
