# Generated by Django 3.2.22 on 2024-01-28 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0005_auto_20240127_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='student_uploads/')),
                ('submission_date', models.DateTimeField(default=datetime.datetime(2024, 1, 28, 0, 30, 4, 173724, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 0, 30, 4, 173724)),
        ),
        migrations.AddField(
            model_name='homework',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='homework_submissions', to='studyswift.HomeworkSubmission'),
        ),
    ]
