# Generated by Django 3.2.22 on 2024-01-28 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0007_auto_20240128_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 0, 37, 16, 334332)),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 0, 37, 16, 334332, tzinfo=utc)),
        ),
    ]
