# Generated by Django 3.2.22 on 2024-01-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0007_auto_20240110_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bad_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='good_points',
            field=models.IntegerField(default=0),
        ),
    ]
