# Generated by Django 3.2.22 on 2024-01-28 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0008_auto_20240128_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 1, 24, 59, 991177)),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 1, 24, 59, 991177, tzinfo=utc)),
        ),
    ]
