# Generated by Django 3.2.22 on 2024-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0008_auto_20240120_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='reward_locker', to='studyswift.Reward'),
        ),
    ]
