# Generated by Django 3.2.22 on 2024-01-29 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0009_alter_homework_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 5, 23, 59, 43, 21218)
            ),
        ),
    ]
