# Generated by Django 3.2.22 on 2024-01-28 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0010_auto_20240128_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='submissions',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 1, 45, 41, 854188)),
        ),
    ]
