# Generated by Django 3.2.22 on 2024-01-30 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0010_auto_20240129_2359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 6, 0, 3, 17, 186757)
            ),
        ),
    ]
