# Generated by Django 3.2.22 on 2024-01-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0010_file_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='files',
            field=models.ManyToManyField(blank=True, to='studyswift.File'),
        ),
    ]
