# Generated by Django 3.2.22 on 2024-01-28 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0011_auto_20240128_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='completed',
            new_name='submissions',
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 1, 56, 59, 442962)),
        ),
    ]
