# Generated by Django 3.2.22 on 2024-01-31 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0011_alter_homework_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 7, 20, 49, 1, 900644)
            ),
        ),
    ]
