# Generated by Django 3.2.22 on 2024-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0011_alter_homework_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
