# Generated by Django 3.2.22 on 2024-02-07 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0012_alter_homework_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='google_calendar_event_id',
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 19, 2, 56, 672056)),
        ),
    ]
