# Generated by Django 3.2.22 on 2024-01-28 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyswift', '0012_auto_20240128_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='submissions',
        ),
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(related_name='homeworks', through='studyswift.HomeworkSubmission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='studyswift.homework'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 13, 34, 23, 655866)),
        ),
    ]
