# Generated by Django 5.0.2 on 2024-02-10 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0013_auto_20240207_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="calendar_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 17, 13, 30, 23, 568376)
            ),
        ),
    ]
