# Generated by Django 3.2.22 on 2024-01-28 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyswift', '0013_auto_20240128_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='file',
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 14, 1, 57, 222082)),
        ),
    ]
