# Generated by Django 5.0.2 on 2024-02-15 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0017_alter_homework_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicevent",
            name="subject",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 22, 12, 27, 2, 157995)
            ),
        ),
    ]
