# Generated by Django 5.0.2 on 2024-03-14 09:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0018_academicevent_subject_alter_homework_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkfile",
            name="studentfile",
            field=models.FileField(blank=True, null=True, upload_to="student_uploads/"),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 21, 9, 35, 39, 116977)
            ),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="rewards",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rewards",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_locker",
                to="studyswift.reward",
            ),
        ),
    ]
