# Generated by Django 5.0.2 on 2024-03-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0023_alter_homework_due_date_exam_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="num_questions",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 24, 11, 33, 8, 755164)
            ),
        ),
    ]
