# Generated by Django 5.0.2 on 2024-03-17 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0025_alter_homework_due_date_alter_question_op1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examsubmission",
            name="submitted_at",
        ),
        migrations.AddField(
            model_name="exam",
            name="marks",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 24, 15, 33, 44, 322599)
            ),
        ),
    ]
