# Generated by Django 5.0.2 on 2024-03-17 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyswift", "0026_remove_examsubmission_submitted_at_exam_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 24, 16, 45, 34, 758693)
            ),
        ),
    ]
